name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14 # You can choose your desired Node.js version

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate with Firebase
        run: |
          echo ${{ secrets.FIREBASE_TOKEN }} | firebase login:ci --no-localhost

      - name: Build and Deploy to Firebase
        run: |
          npm install
          npm run build # Modify this command according to your Vue.js project's build setup
          firebase deploy --token "$FIREBASE_TOKEN" --only hosting

